name: Black Duck Scan 
on:
  push:
    branches: [ badges ]
jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Black Duck Scan
        uses: synopsys-sig/synopsys-action@v1.8.0
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        with:
          blackduck_url: ${{ secrets.BLACKDUCK_URL_VALID01 }}
          blackduck_token: ${{ secrets.BLACKDUCK_TOKEN_VALID01 }}
          # github_token: ${{ secrets.GITHUB_TOKEN }}
